  method FUNCTION_V1.
    WRITE 'THIS IS THE FIRST METHOOD FOR TESTING GCTS VIA RO'.
    WRITE 'I HAVE ADDED THIS LINE FROM GIT SOFTWARE'.
    WRITE 'I HAVE ADDED THIS FROM ABAP WORK BENCH '.
  endmethod.