  method FUNCTION_V1.
    WRITE 'THIS IS THE FIRST METHOOD FOR TESTING GCTS VIA RO'.
    WRITE 'I HAVE ADDED THIS LINE FROM GIT SOFTWARE'.
    WRITE 'this line is edited in workbench'.
    WRITE 'THIS IS EDITED FROM THE GIT FOR TESTING NEW BRANCHES'.
  endmethod.
